name: q6-reusable

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use greeting action
        id: greet
        uses: ./.github/actions/greet
        with:
          name: ${{ inputs.target_env }}
          greeting: Hello

      - name: Show message
        run: |
          echo "Hello ${{ inputs.target_env }}"
          echo "Deploying to ${{ inputs.target_env }} environment"
